config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { invitations: 'users/invitations', registrations: 'custom_devise_controllers/registrations' }

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :groups do
    post 'invite', to: 'groups#invite_to_group', as: :invite_to_group
    resources :routines do
      resources :categories
      post 'add_exercise/:exercise_id', to: 'routines#add_exercise', as: 'add_exercise'
      resources :exercises
      resources :routine_exercises, only: [:update, :destroy]
      patch 'update_exercises', on: :member
    end
  end
  resources :workout_sessions, only: [:create, :show, :update] do
    patch :update_exercises, on: :member
    resources :session_exercises
    member do
      patch :end_session
    end
  end
  root "groups#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :exercises
  belongs_to :user, optional: true
end

app/models/exercise.rb
class Exercise < ApplicationRecord
  belongs_to :category
  belongs_to :exercise_type
  belongs_to :user, optional: true

  has_many :group_exercises
  has_many :groups, through: :group_exercises
end

app/models/exercise_type.rb
class ExerciseType < ApplicationRecord
end

app/models/group.rb
class Group < ApplicationRecord

  belongs_to :created_by_user, class_name: 'User'
  has_many :group_members
  has_many :users, through: :group_members
  has_many :routines
  has_many :workout_sessions

  has_many :invitation_group_associations

  has_many :group_exercises
  has_many :exercises, through: :group_exercises

end

app/models/group_exercise.rb
class GroupExercise < ApplicationRecord
  belongs_to :exercise
  belongs_to :group
end

app/models/group_member.rb
class GroupMember < ApplicationRecord

  belongs_to :user
  belongs_to :group
end

app/models/routine.rb
class Routine < ApplicationRecord
  belongs_to :user
  belongs_to :group
  has_many :workout_sessions
  has_many :routine_exercises

  accepts_nested_attributes_for :routine_exercises
end

app/models/routine_exercise.rb
class RoutineExercise < ApplicationRecord
  has_many :session_exercises, dependent: :destroy
  belongs_to :routine
  belongs_to :exercise
end

app/models/session.rb
class Session < ApplicationRecord
  belongs_to :routine
  belongs_to :user
  belongs_to :group
  has_many :session_exercises, dependent: :destroy

  def ended?
    end_time.present?
  end

end

app/models/session_exercise.rb
class SessionExercise < ApplicationRecord
  serialize :set_details, Array

  belongs_to :routine_exercise
  belongs_to :workout_session
  belongs_to :exercise
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :invitable, :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :group_members
  has_many :groups, through: :group_members
  has_many :routines
  has_many :workout_sessions
  has_many :exercises
  has_many :categories

  def self.invite!(attributes = {}, invited_by = nil)
    invited_user = super(attributes.except(:group_id), invited_by)
    user = User.find_by(email: invited_user.email)
    if user
      group = Group.find(attributes[:group_id])
      unless GroupMember.exists?(user: user, group: group)
        GroupMember.create(user: user, group: group)
      end
    else
      if invited_user.persisted? && attributes[:group_id]
        InvitationGroupAssociation.create!(
          email: invited_user.email,
          group_id: attributes[:group_id],
          invitation_token: invited_user.raw_invitation_token
        )
      end
    end
    invited_user
  end
end

app/models/workout_session.rb
class WorkoutSession < ApplicationRecord
  belongs_to :routine
  belongs_to :user
  belongs_to :group
  has_many :session_exercises

  accepts_nested_attributes_for :session_exercises

  def ended?
    end_time.present?
  end
end

app/controllers/routines_controller.rb
class RoutinesController < ApplicationController

  def index
    @routines = Routine.where(group_id: params[:group_id])
  end

  def show
    @routine = Routine.find(params[:id])
  end

  def new
    @routine = Routine.new
    @group = Group.find(params[:group_id])
  end

  def edit
  end

  def create
    @routine = Routine.new(routine_params)
    @routine.group = Group.find(params[:group_id])
    @routine.user = current_user

    if @routine.save
      redirect_to group_path(@routine.group), notice: 'Routine was successfully created.'
    else
      render :new
    end
  end

  def update
    if @routine.update(routine_params)
      redirect_to @routine, notice: 'Routine was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @routine = Routine.find(params[:id])
    @group = Group.find(params[:group_id])
    if @routine.destroy
      redirect_to group_path(@group), notice: 'Routine was successfully destroyed.'
    end
  end

  # CUSTOM CONTROLLER ACTIONS
  #
  def add_exercise
    @routine = Routine.find(params[:routine_id])
    exercise = Exercise.find(params[:exercise_id])

    RoutineExercise.create!(routine: @routine, exercise: exercise)

    redirect_to group_routine_path(@routine.group_id, @routine), notice: 'Exercise added successfully'
  end

  def update_exercises
    @routine = Routine.find(params[:id])

    routine_exercises_params[:routine_exercises].each do |id, exercise_params|
      routine_exercise = @routine.routine_exercises.find(id)
      routine_exercise.update(sets: exercise_params[:sets])
    end
  end

  private

  def routine_params
    params.require(:routine).permit(:name, :description)
  end

  def routine_exercises_params
    params.require(:routine).permit(routine_exercises: [:id, :sets])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/exercises_helper.rb
module ExercisesHelper
end

app/helpers/group_members_helper.rb
module GroupMembersHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/routines_helper.rb
module RoutinesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def last_value_for_exercise(exercise, attribute)
    SessionExercise.joins(:routine_exercise)
                   .where(routine_exercises: { exercise_id: exercise.id })
                   .order(created_at: :desc)
                   .pick(attribute) || 0
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/routines/_form.html.erb
  <%= form_with model: @routine, url: group_routines_path(@group), data: { turbo_method: :post } do |f| %>
    <%= f.label :name, "Routine Name", class: "block text-sm font-medium leading-6 text-gray-900"%>
    <%= f.text_field :name, required: true, class: "block rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6" %>
    <%= f.label :description, "Description", class: "block text-sm font-medium leading-6 text-gray-900"%>
    <%= f.text_field :description, class: "block rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6" %>
    <%= f.submit "Create Routine", class: "mt-3 rounded-md bg-white px-3 py-2 text-sm font-semibold text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 hover:bg-gray-50" %>
  <% end %>

app/views/routines/new.html.erb
<div class="flex flex-col mb-4 md:mb-2 justify-between md:flex-row">
  <div>
    <h1 class="text-4xl mb-1">New Routine</h1>
  </div>
  <%= link_to 'Back to Group', :back, class: "self-start md:self-center rounded-md bg-white px-3 py-2 text-sm font-semibold text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 hover:bg-gray-50" %>
</div>

<%= render 'form', routine: @routine, group: @group %>

app/views/routines/show.html.erb
<div class="flex flex-col mb-4 md:mb-2 justify-between md:flex-row">
  <div>
    <h1 class="text-4xl mb-1"><%= @routine.name %></h1>
    <h2 class="text-xl mb-2 text-gray-600 "><%= @routine.description %></h2>
  </div>
  <div>
    <%= link_to 'Delete Routine', group_routine_path(@routine.group, @routine), data: { turbo_method: :delete }, class: "self-start md:self-center rounded-md bg-white px-3 py-2 text-sm font-semibold text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 hover:bg-red-100 bg-red-200"%>
    <%= link_to 'Back to Routines', group_path(@routine.group), class: "self-start md:self-center rounded-md bg-white px-3 py-2 text-sm font-semibold text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 hover:bg-gray-50" %>
  </div>
</div>

<%= form_with(model: @routine, url: update_exercises_group_routine_path(@routine.group, @routine), method: :patch, local: true) do |form| %>
  <div class="mt-8 flex flex-col mb-6 md:mb-10 justify-between md:flex-row">
    <h2 class="text-xl mb-2">Exercises</h2>
    <div>
      <%= link_to 'Start Workout Session', workout_sessions_path(routine_id: @routine.id), data: { turbo_method: :post }, class: "bg-green-200 rounded-md bg-white px-3 py-2 text-sm font-semibold text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 hover:bg-green-100 self-start md:self-center" %>
      <%= link_to 'Add Exercise', group_routine_exercises_path(@routine.group, @routine), class: "rounded-md bg-white px-3 py-2 text-sm font-semibold text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 hover:bg-gray-50 self-start md:self-center" %>
    </div>
  </div>
  <div class="flex flex-col space-y-2">
    <% @routine.routine_exercises.each do |routine_exercise| %>
      <div class="flex flex-col sm:flex-row items-center space-y-2 sm:space-y-0 sm:space-x-2 bg-white shadow-sm ring-1 ring-gray-300 sm:rounded-lg p-4">
        <div class="flex-grow">
          <%= routine_exercise.exercise.name %>
        </div>
        <%= form.fields_for 'routine_exercises[]', routine_exercise do |re_form| %>
          <%= re_form.hidden_field :id %>
          <div class="flex-grow">
            Sets <%= re_form.number_field :sets, class: "w-full sm:w-auto rounded-md border-gray-300 shadow-sm focus:border-indigo-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50" %>
          </div>
          <%= link_to 'Remove', group_routine_routine_exercise_path(@routine.group, @routine, routine_exercise), method: :delete, data: { turbo_method: :delete, confirm: 'Are you sure?' }, class: "text-red-600 hover:text-red-700" %>
        <% end %>
      </div>
    <% end %>
  </div>
  <div class="mt-4">
    <%= form.submit "Update Sets", class: "rounded-md bg-white px-3 py-2 text-sm font-semibold text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 hover:bg-gray-50 self-start md:self-center" %>
  </div>
<% end %>