config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { invitations: 'users/invitations', registrations: 'custom_devise_controllers/registrations' }

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :groups do
    post 'invite', to: 'groups#invite_to_group', as: :invite_to_group
    resources :routines do
      resources :categories
      post 'add_exercise/:exercise_id', to: 'routines#add_exercise', as: 'add_exercise'
      resources :exercises
      resources :routine_exercises, only: [:update, :destroy]
      patch 'update_exercises', on: :member
    end
  end
  resources :workout_sessions, only: [:create, :show, :update] do
    patch :update_exercises, on: :member
    resources :session_exercises
    member do
      patch :end_session
    end
  end
  root "groups#index"
end

app/models/workout_session.rb
class WorkoutSession < ApplicationRecord
  belongs_to :routine
  belongs_to :user
  belongs_to :group
  has_many :session_exercises

  accepts_nested_attributes_for :session_exercises

  def ended?
    end_time.present?
  end
end

app/controllers/workout_sessions_controller.rb
class WorkoutSessionsController < ApplicationController
  include WorkoutSessionsHelper
  before_action :set_session, only: [:show, :edit, :update, :destroy]

  def index
    @workout_sessions = WorkoutSession.where(routine_id: params[:routine_id])
  end

  def show
    @workout_session = WorkoutSession.includes(:session_exercises).find(params[:id])

    # Assuming each routine exercise is part of the workout session
    @workout_session.routine.routine_exercises.each do |routine_exercise|
      # Check if a session exercise for this routine exercise already exists in this workout session
      session_exercise = @workout_session.session_exercises.find_by(exercise_id: routine_exercise.exercise_id)

      unless session_exercise
        # Fetch last values or default values
        last_values = last_values_for_exercise(routine_exercise.exercise, current_user, routine_exercise.sets)

        # Build a new session exercise with the last or default values
        @workout_session.session_exercises.build(
          exercise_id: routine_exercise.exercise_id,
          set_details: Array.new(routine_exercise.sets) { last_values }
        )
      end
    end
  end

  def new
    @workout_session = WorkoutSession.new
  end

  def edit
  end

  def create
    @routine = Routine.find(params[:routine_id])
    @group = @routine.group
    @workout_session = WorkoutSession.new(routine: @routine, start_time: Time.current, user: current_user, group: @group)
    @workout_session.routine.routine_exercises.each do |routine_exercise|
      last_values = last_values_for_exercise(routine_exercise.exercise, current_user, routine_exercise.sets)

      session_exercise = @workout_session.session_exercises.build(
        exercise_id: routine_exercise.exercise_id,
        set_details: last_values,
        routine_exercise_id: routine_exercise.id
      )

    end
    if @workout_session.save
      redirect_to workout_session_path(@workout_session), notice: 'Session started successfully.'
    else
      redirect_to group_routine_path(@routine.group_id, @routine), alert: 'Error starting workout_session.'
    end
  end

  def destroy
    @workout_session.destroy
    redirect_to workout_sessions_url, notice: 'Session was successfully destroyed.'
  end

  # CUSTOM CONTROLLER ACTIONS

  def end_session
    @workout_session = WorkoutSession.find(params[:id])
    if @workout_session.update(end_time: Time.current)
      redirect_to workout_session_path(@workout_session), notice: 'Session ended.'
    else
      redirect_to workout_session_path(@workout_session), alert: 'Could not end the workout_session. Please try again.'
    end
  end

  def update
    @workout_session = WorkoutSession.find(params[:id])

    session_exercises_attrs = params.dig(:workout_session, :session_exercises_attributes)

    ActiveRecord::Base.transaction do
      session_exercises_attrs&.each do |_key, attrs|
        session_exercise = @workout_session.session_exercises.find(attrs[:id])

        if attrs[:set_details].is_a?(Array)
          # Assuming set_details is an array of hashes
          set_details_array = attrs[:set_details].map(&:to_unsafe_h).map(&:to_h)
          session_exercise.set_details = set_details_array
        end

        session_exercise.save!
      end
    end

    redirect_to @workout_session, notice: 'Session updated successfully.'
  rescue ActiveRecord::RecordInvalid => e
    render :edit, status: :unprocessable_entity
  end

  private

  def set_session
    @workout_session = WorkoutSession.find(params[:id])
  end

  def workout_session_params
    params.require(:workout_session).permit(
      :start_time, :end_time, :bodyweight, :notes, :routine_id,
      session_exercises_attributes: [
        :id,
        { set_details: [:reps, :weight, :note] }
      ]
    )
  end

  def session_exercises_params
    params.require(:session_exercises).map do |_, exercise_params|
      exercise_params.permit(:id, set_details: [:reps, :weight, :note])
    end
  end

  def update_set_details
    params[:session_exercises].each_with_index do |session_exercise_param, index|
      session_exercise = @workout_session.session_exercises.find(session_exercise_param[:id])
      session_exercise.update(set_details: session_exercise_param[:set_details].values)
    end
  end

end

app/helpers/workout_sessions_helper.rb
module WorkoutSessionsHelper
  def last_values_for_exercise(exercise, user, number_of_sets)
    last_session_exercise = SessionExercise
                              .joins(:workout_session)
                              .where(exercise_id: exercise.id, workout_sessions: { user_id: user.id })
                              .order(created_at: :desc)
                              .first

    # This will hold the final set details, either from the last session or default values
    set_details_array = Array.new(number_of_sets) { { 'reps' => 0, 'weight' => 0, 'note' => '' } }

    if last_session_exercise.present?
      # Take as many last set details as needed, up to the number_of_sets
      last_set_details = last_session_exercise.set_details.take(number_of_sets)
      last_set_details.each_with_index do |set_detail, index|
        set_details_array[index] = set_detail
      end
    end

    set_details_array
  end
end

app/views/workout_sessions/_active_session_fields.html.erb
<%= form.fields_for :session_exercises do |session_exercise_form| %>
<div class="rounded-md border-gray-300 shadow-sm bg-gray-100 p-5 my-5">
  <table class="min-w-full divide-y divide-gray-300 mb-10">
    <thead>
      <h2 class="text-xl mb-2"><%= session_exercise_form.object.exercise.name %></h2>
      <tr>
        <th scope="col" class="py-3.5 pl-4 pr-3 text-left text-sm font-semibold text-gray-900 sm:pl-6">Weight</th>
        <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Reps</th>
        <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Note</th>
      </tr>
    </thead>
    <tbody>
      <% session_exercise_form.object.set_details.each_with_index do |set_detail, index| %>
        <tr>
          <td class="relative py-4 pl-4 pr-3 text-sm sm:pl-6">
            <div class="font-medium text-gray-900">
              <%= session_exercise_form.number_field :reps, value: set_detail['reps'], name: "workout_session[session_exercises_attributes][#{session_exercise_form.index}][set_details][][reps]", class: "w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50" %>
            </div>
          </td>
          <td class="relative py-4 pl-4 pr-3 text-sm ">
            <div class="font-medium text-gray-900">
              <%= session_exercise_form.number_field :weight, value: set_detail['weight'], name: "workout_session[session_exercises_attributes][#{session_exercise_form.index}][set_details][][weight]", class: "w-full  rounded-md border-gray-300 shadow-sm focus:border-indigo-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50" %>
            </div>
          </td>
          <td class="relative py-4 pl-4 pr-3 text-sm">
            <div class="font-medium text-gray-900">
              <%= session_exercise_form.text_field :note, value: set_detail['note'], name: "workout_session[session_exercises_attributes][#{session_exercise_form.index}][set_details][][note]", class: "w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50" %>
            </div>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
  </div>
<% end %>

app/views/workout_sessions/show.html.erb
<div class="flex flex-col mb-8 md:mb-10 justify-between md:flex-row">
  <div>
    <h1 class="text-4xl mb-1"><%= @workout_session.user.name %>'s <%= @workout_session.routine.name %> Session</h1>
    <% Time.zone = 'Perth'%>
    <p>Started at: <%= @workout_session.start_time.in_time_zone.strftime('%H:%M, %d/%m/%Y') %></p>
    <p class="mb-3">End time: 
      <% if @workout_session.ended? %>
        <%= @workout_session.end_time.strftime('%H:%M, %d/%m/%Y') %>  
      <% end %>
    </p>
    <%= link_to 'Back to Groups', group_path(@workout_session.routine.group), class: "self-start md:self-center rounded-md bg-white px-3 py-2 text-sm font-semibold text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 hover:bg-gray-50" %>
  </div>
</div>
<%= form_with(model: @workout_session, local: true) do |form| %>
  <%= render 'active_session_fields', form: form %>
  <%= form.submit "Save Current Details", class: "mt-3 rounded-md bg-white px-3 py-2 text-sm font-semibold text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 hover:bg-gray-50" %>
  <% if !@workout_session.ended?%>
    <%= link_to 'Finish Session', end_session_workout_session_path(@workout_session), data: { turbo_method: :patch }, class: "mt-3 rounded-md bg-white px-3 py-2 text-sm font-semibold text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 hover:bg-gray-50" %>
  <% end %>
<% end %>