config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { invitations: 'users/invitations', registrations: 'custom_devise_controllers/registrations' }

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :groups do
    post 'invite', to: 'groups#invite_to_group', as: :invite_to_group
    resources :routines do
      resources :categories
      post 'add_exercise/:exercise_id', to: 'routines#add_exercise', as: 'add_exercise'
      resources :exercises
      resources :routine_exercises, only: [:update, :destroy]
      patch 'update_exercises', on: :member
    end
  end
  resources :workout_sessions, only: [:create, :show, :update] do
    patch :update_exercises, on: :member
    resources :session_exercises
    member do
      patch :end_session
    end
  end
  root "groups#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :exercises
  belongs_to :user, optional: true
end

app/models/exercise.rb
class Exercise < ApplicationRecord
  belongs_to :category
  belongs_to :exercise_type
  belongs_to :user, optional: true

  has_many :group_exercises
  has_many :groups, through: :group_exercises
end

app/models/exercise_type.rb
class ExerciseType < ApplicationRecord
end

app/models/group.rb
class Group < ApplicationRecord

  belongs_to :created_by_user, class_name: 'User'
  has_many :group_members
  has_many :users, through: :group_members
  has_many :routines
  has_many :workout_sessions

  has_many :invitation_group_associations

  has_many :group_exercises
  has_many :exercises, through: :group_exercises

end

app/models/group_exercise.rb
class GroupExercise < ApplicationRecord
  belongs_to :exercise
  belongs_to :group
end

app/models/group_member.rb
class GroupMember < ApplicationRecord

  belongs_to :user
  belongs_to :group
end

app/models/routine.rb
class Routine < ApplicationRecord
  belongs_to :user
  belongs_to :group
  has_many :workout_sessions
  has_many :routine_exercises

  accepts_nested_attributes_for :routine_exercises
end

app/models/routine_exercise.rb
class RoutineExercise < ApplicationRecord
  has_many :session_exercises, dependent: :destroy
  belongs_to :routine
  belongs_to :exercise
end

app/models/session.rb
class Session < ApplicationRecord
  belongs_to :routine
  belongs_to :user
  belongs_to :group
  has_many :session_exercises, dependent: :destroy

  def ended?
    end_time.present?
  end

end

app/models/session_exercise.rb
class SessionExercise < ApplicationRecord
  serialize :set_details, Array

  belongs_to :routine_exercise
  belongs_to :workout_session
  belongs_to :exercise
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :invitable, :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :group_members
  has_many :groups, through: :group_members
  has_many :routines
  has_many :workout_sessions
  has_many :exercises
  has_many :categories

  def self.invite!(attributes = {}, invited_by = nil)
    invited_user = super(attributes.except(:group_id), invited_by)
    user = User.find_by(email: invited_user.email)
    if user
      group = Group.find(attributes[:group_id])
      unless GroupMember.exists?(user: user, group: group)
        GroupMember.create(user: user, group: group)
      end
    else
      if invited_user.persisted? && attributes[:group_id]
        InvitationGroupAssociation.create!(
          email: invited_user.email,
          group_id: attributes[:group_id],
          invitation_token: invited_user.raw_invitation_token
        )
      end
    end
    invited_user
  end
end

app/models/workout_session.rb
class WorkoutSession < ApplicationRecord
  belongs_to :routine
  belongs_to :user
  belongs_to :group
  has_many :session_exercises

  accepts_nested_attributes_for :session_exercises

  def ended?
    end_time.present?
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:show, :edit, :update, :destroy]
  before_action :check_membership, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  def index
    @owned_groups = Group.where(created_by_user: current_user)
    @member_groups = Group.joins(:group_members)
                      .where(group_members: { user_id: current_user.id })
                      .where.not(created_by_user: current_user)
  end

  def new
    @group = Group.new
  end

  def create
    @group = Group.new(group_params)
    @group.created_by_user = current_user

    if @group.save
      # Automatically create a membership for the user who created the group
      GroupMember.create!(group: @group, user: current_user)

      redirect_to @group, notice: 'Group was successfully created.'
    else
      render :new
    end
  end

  def show
    @group = Group.find(params[:id])
    @routines = @group.routines
    @workout_sessions = @group.workout_sessions
  end

  # CUSTOM CONTROLLER ACTIONS
  def invite_to_group
    user_email = params[:email]
    group_id = params[:group_id]

    User.invite!({email: user_email, group_id: group_id}, current_user)
    redirect_to group_path(group_id), notice: "Invitation sent to #{user_email}"
  end

  private

  def group_params
    params.require(:group).permit(:name, :description, :user_id)
  end

  def set_group
    @group = Group.find(params[:id])
  end

  def check_membership
    unless @group.created_by_user == current_user ||
           @group.group_members.exists?(user_id: current_user.id)
      redirect_to groups_path, alert: 'You do not have permission to access this group.'
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/exercises_helper.rb
module ExercisesHelper
end

app/helpers/group_members_helper.rb
module GroupMembersHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/routines_helper.rb
module RoutinesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def last_value_for_exercise(exercise, attribute)
    SessionExercise.joins(:routine_exercise)
                   .where(routine_exercises: { exercise_id: exercise.id })
                   .order(created_at: :desc)
                   .pick(attribute) || 0
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/groups/_form.html.erb
<%= form_with(model: @group, url: groups_path(@group), method: :post) do |f| %>
  <%= f.label :name, "Group Name", class: "block text-sm font-medium leading-6 text-gray-900"%>
  <%= f.text_field :name, required: true, class: "block rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6" %>
  <%= f.label :description, "Description", class: "block text-sm font-medium leading-6 text-gray-900"%>
  <%= f.text_field :description, class: "block rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6" %>
  <%= f.submit "Create Group", class: "mt-3 rounded-md bg-white px-3 py-2 text-sm font-semibold text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 hover:bg-gray-50" %>
<% end %>

app/views/groups/index.html.erb
<h1 class="text-4xl mb-4">Groups</h1>

<div class="flex flex-col mb-6 md:mb-2 justify-between md:flex-row">
  <h2 class="text-2xl font-semibold mb-2">Your groups</h2>
  <div>
    <%= link_to 'Create new Group', new_group_path, class: "rounded-md bg-white px-3 py-2 text-sm font-semibold text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 hover:bg-gray-50" %>
    <%= link_to 'Sign out', destroy_user_session_path, data: { turbo_method: :delete }, class: "rounded-md bg-white px-3.5 py-2 text-sm font-semibold text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 hover:bg-gray-50" %>
  </div>
</div>

<% if @owned_groups.empty? %>
    <p class="text-gray-600">You do not own any groups.</p>
<% else %>
  <ul role="list" class="divide-y divide-gray-100 overflow-hidden bg-white shadow-sm ring-1 ring-gray-900/5 sm:rounded-xl">
    <% @owned_groups.each do |group| %>
      <%= link_to(group) do %>
        <li class="relative flex justify-between items-center gap-x-6 px-4 py-5 hover:bg-gray-50 sm:px-6">
          <div class="flex min-w-0 gap-x-4">
            <div class="min-w-0 flex-auto">
              <p class="text-sm font-semibold text-gray-900">
                <%= group.name %> <br/>
              </p>
              <p class="text-sm font-light text-gray-400 ">
                <%= group.description %>
              </p>
            </div>
          </div>
          <svg class="h-5 w-5 text-gray-400 flex" width="20" height="20" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true" >
            <path fill-rule="evenodd" d="M7.21 14.77a.75.75 0 01.02-1.06L11.168 10 7.23 6.29a.75.75 0 111.04-1.08l4.5 4.25a.75.75 0 010 1.08l-4.5 4.25a.75.75 0 01-1.06-.02z" clip-rule="evenodd" />
          </svg>
        </li>
      <% end %>
    <% end %>
  </ul>
<% end %>

<h2 class="text-2xl font-semibold mb-2 mt-6">Joined groups</h2>
<% if @member_groups.empty? %>
  <p class="text-gray-600">You are not a member of any groups.</p>
<% else %>
  <ul role="list" class="divide-y divide-gray-100 overflow-hidden bg-white shadow-sm ring-1 ring-gray-900/5 sm:rounded-xl">
    <% @member_groups.each do |group| %>
      <%= link_to(group) do %>
        <li class="relative flex justify-between items-center gap-x-6 px-4 py-5 hover:bg-gray-50 sm:px-6">
          <div class="flex min-w-0 gap-x-4">
            <div class="min-w-0 flex-auto">
              <p class="text-sm font-semibold text-gray-900">
                <%= group.name %> <br/>
              </p>
              <p class="text-sm font-light text-gray-400 ">
                <%= group.description %>
              </p>
            </div>
          </div>
          <svg class="h-5 w-5 text-gray-400 flex" width="20" height="20" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true" >
            <path fill-rule="evenodd" d="M7.21 14.77a.75.75 0 01.02-1.06L11.168 10 7.23 6.29a.75.75 0 111.04-1.08l4.5 4.25a.75.75 0 010 1.08l-4.5 4.25a.75.75 0 01-1.06-.02z" clip-rule="evenodd" />
          </svg>
        </li>
      <% end %>
    <% end %>
  </ul>
<% end %>

app/views/groups/new.html.erb
<div class="flex flex-col mb-4 md:mb-2 justify-between md:flex-row">
  <div>
    <h1 class="text-4xl mb-1">New Group</h1>
  </div>
  <%= link_to 'Back to Groups', :back, class: "self-start md:self-center rounded-md bg-white px-3 py-2 text-sm font-semibold text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 hover:bg-gray-50" %>
</div>

<%= render 'form', group: @group %>

app/views/groups/show.html.erb
<div class="flex flex-col mb-4 md:mb-2 justify-between md:flex-row">
  <div>
    <h1 class="text-4xl mb-1"><%= @group.name %></h1>
    <h2 class="text-xl mb-2 text-gray-600 "><%= @group.description %></h2>
  </div>
</div>

<%= link_to 'Back to Groups', groups_path, class: "rounded-md bg-white px-3 py-2 text-sm font-semibold text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 hover:bg-gray-50" %>


<div class="mt-8 mb-6 md:mb-10">
  <h2 class="text-xl mb-2 ">Invite a friend</h2>
  <%= form_with url: group_invite_to_group_path(@group), method: :post do |f| %>
    <%= f.label :email, "Email", class: "block text-sm font-medium leading-6 text-gray-900"%>
    <%= f.email_field :email, required: true, class: "block rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6", placeholder: "you@example.com" %>
    <%= f.hidden_field :group_id, value: @group.id %>
    <%= f.submit "Invite User", class: "mt-3 rounded-md bg-white px-3 py-2 text-sm font-semibold text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 hover:bg-gray-50" %>
  <% end %>
</div>

<div class="flex flex-col mb-6 md:mb-2 justify-between md:flex-row">
  <h2 class="text-xl mb-2 ">Routines</h2>
  <div>
    <%= link_to "Add Routine", new_group_routine_path(@group), class: "rounded-md bg-white px-3 py-2 text-sm font-semibold text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 hover:bg-gray-50" %>
  </div>
</div>
<% if @routines.any? %>
  <ul role="list" class="divide-y divide-gray-100 overflow-hidden bg-white shadow-sm ring-1 ring-gray-900/5 sm:rounded-xl">
    <% @routines.each do |routine| %>
      <%= link_to group_routine_path(@group, routine) do %>
        <li class="relative flex justify-between items-center gap-x-6 px-4 py-5 hover:bg-gray-50 sm:px-6">
          <div class="flex min-w-0 gap-x-4">
            <div class="min-w-0 flex-auto">
              <p class="text-sm font-semibold text-gray-900">
                <%= routine.name %> <br/>
              </p>
              <p class="text-sm font-light text-gray-400 ">
                <%= routine.description %>
              </p>
            </div>
          </div>
          <svg class="h-5 w-5 text-gray-400 flex" width="20" height="20" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true" >
            <path fill-rule="evenodd" d="M7.21 14.77a.75.75 0 01.02-1.06L11.168 10 7.23 6.29a.75.75 0 111.04-1.08l4.5 4.25a.75.75 0 010 1.08l-4.5 4.25a.75.75 0 01-1.06-.02z" clip-rule="evenodd" />
          </svg>
        </li>
      <% end %>
    <% end %>
  </ul>
<% else %>
  <p class="text-gray-600">There are no routines in this group.</p>
<% end %>

<div class="flex flex-col mt-6 md:mt-10 mb-6 md:mb-2 justify-between md:flex-row">
  <h2 class="text-xl mb-2 ">Sessions</h2>
</div>
<% if @workout_sessions.any? %>
  <ul role="list" class="divide-y divide-gray-100 overflow-hidden bg-white shadow-sm ring-1 ring-gray-900/5 sm:rounded-xl">
    <% @workout_sessions.each do |workout_session| %>
      <%= link_to workout_session_path(workout_session) do %>
        <li class="relative flex justify-between items-center gap-x-6 px-4 py-5 hover:bg-gray-50 sm:px-6">
          <div class="flex min-w-0 gap-x-4">
            <div class="min-w-0 flex-auto">
              <p class="text-sm font-semibold text-gray-900">
                <%= workout_session.user.name %>
              </p>
              <% if workout_session.ended?%>
                <p class="text-sm font-semibold text-green-500">
                  Finished
                </p>
              <% else %>
                <p class="text-sm font-semibold text-gray-500">
                  In progress
                </p>
              <% end %>
              <p class="text-sm font-light text-gray-400 ">
                <% Time.zone = 'Perth' %>
                <%= workout_session.routine.name %> - <%= workout_session.start_time.in_time_zone.strftime('%d/%m/%Y') %>
              </p>
            </div>
          </div>
          <svg class="h-5 w-5 text-gray-400 flex" width="20" height="20" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true" >
            <path fill-rule="evenodd" d="M7.21 14.77a.75.75 0 01.02-1.06L11.168 10 7.23 6.29a.75.75 0 111.04-1.08l4.5 4.25a.75.75 0 010 1.08l-4.5 4.25a.75.75 0 01-1.06-.02z" clip-rule="evenodd" />
          </svg>
        </li>
      <% end %>
    <% end %>
  </ul>
<% else %>
  <p class="text-gray-600">No sessions recorded for this group</p>
<% end %>