config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { invitations: 'users/invitations', registrations: 'custom_devise_controllers/registrations' }

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :groups do
    post 'invite', to: 'groups#invite_to_group', as: :invite_to_group
    resources :routines do
      resources :categories
      post 'add_exercise/:exercise_id', to: 'routines#add_exercise', as: 'add_exercise'
      resources :exercises
      resources :routine_exercises, only: [:update, :destroy]
      patch 'update_exercises', on: :member
    end
  end
  resources :workout_sessions, only: [:create, :show, :update] do
    patch :update_exercises, on: :member
    resources :session_exercises
    member do
      patch :end_session
    end
  end
  root "groups#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :exercises
  belongs_to :user, optional: true
end

app/models/exercise.rb
class Exercise < ApplicationRecord
  belongs_to :category
  belongs_to :exercise_type
  belongs_to :user, optional: true

  has_many :group_exercises
  has_many :groups, through: :group_exercises
end

app/models/exercise_type.rb
class ExerciseType < ApplicationRecord
end

app/models/group.rb
class Group < ApplicationRecord

  belongs_to :created_by_user, class_name: 'User'
  has_many :group_members
  has_many :users, through: :group_members
  has_many :routines
  has_many :workout_sessions

  has_many :invitation_group_associations

  has_many :group_exercises
  has_many :exercises, through: :group_exercises

end

app/models/group_exercise.rb
class GroupExercise < ApplicationRecord
  belongs_to :exercise
  belongs_to :group
end

app/models/group_member.rb
class GroupMember < ApplicationRecord

  belongs_to :user
  belongs_to :group
end

app/models/routine.rb
class Routine < ApplicationRecord
  belongs_to :user
  belongs_to :group
  has_many :workout_sessions
  has_many :routine_exercises

  accepts_nested_attributes_for :routine_exercises
end

app/models/routine_exercise.rb
class RoutineExercise < ApplicationRecord
  has_many :session_exercises, dependent: :destroy
  belongs_to :routine
  belongs_to :exercise
end

app/models/session.rb
class Session < ApplicationRecord
  belongs_to :routine
  belongs_to :user
  belongs_to :group
  has_many :session_exercises, dependent: :destroy

  def ended?
    end_time.present?
  end

end

app/models/session_exercise.rb
class SessionExercise < ApplicationRecord
  serialize :set_details, Array

  belongs_to :routine_exercise
  belongs_to :workout_session
  belongs_to :exercise
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :invitable, :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :group_members
  has_many :groups, through: :group_members
  has_many :routines
  has_many :workout_sessions
  has_many :exercises
  has_many :categories

  def self.invite!(attributes = {}, invited_by = nil)
    invited_user = super(attributes.except(:group_id), invited_by)
    user = User.find_by(email: invited_user.email)
    if user
      group = Group.find(attributes[:group_id])
      unless GroupMember.exists?(user: user, group: group)
        GroupMember.create(user: user, group: group)
      end
    else
      if invited_user.persisted? && attributes[:group_id]
        InvitationGroupAssociation.create!(
          email: invited_user.email,
          group_id: attributes[:group_id],
          invitation_token: invited_user.raw_invitation_token
        )
      end
    end
    invited_user
  end
end

app/models/workout_session.rb
class WorkoutSession < ApplicationRecord
  belongs_to :routine
  belongs_to :user
  belongs_to :group
  has_many :session_exercises

  accepts_nested_attributes_for :session_exercises

  def ended?
    end_time.present?
  end
end

app/controllers/exercises_controller.rb
class ExercisesController < ApplicationController

  def index
    @routine = Routine.where(group_id: current_group.id).find(params[:routine_id])
      # Fetch categories that are global or belong to the current user
    @categories = Category.where(user_id: [current_user.id, nil])

    # Create a hash to store exercises for each category
    @category_exercises = {}

    # For each category, store filtered exercises in the hash
    @categories.each do |category|
      @category_exercises[category.id] = category.exercises.where(user_id: [current_user.id, nil])
    end
  end

  def new
    @routine = Routine.find(params[:routine_id])
    @group = Group.find(params[:group_id])
    @exercise = Exercise.new
    @categories = Category.where(user: [current_user, nil])
    @exercise_types = ExerciseType.all
  end

  def create
    @routine = Routine.find(params[:routine_id])
    @group = Group.find(params[:group_id])
    @exercise = current_user.exercises.build(exercise_params)

    if @exercise.save
      GroupExercise.create(exercise: @exercise, group: @group)
      redirect_to group_routine_exercises_path(@group, @routine), notice: 'Exercise was successfully added.'
    else
      render :new
    end
  end

  # CUSTOM CONTROLLER ACTIONS
  def copy_to_my_exercises
    group_exercise = GroupExercise.find(params[:id])
    new_exercise = current_user.exercises.create(group_exercise.exercise.attributes.except('id', 'created_at', 'updated_at', 'user_id'))

    if new_exercise.persisted?
      redirect_to my_exercises_path, notice: 'Exercise copied to your list.'
    else
      redirect_to group_path(group_exercise.group_id), alert: 'Unable to copy exercise.'
    end
  end

  private

  def exercise_params
    params.require(:exercise).permit(:name, :category_id, :exercise_type_id, :user_id, :routine_id)
  end

  def current_group
    @current_group ||= Group.find(params[:group_id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/exercises_helper.rb
module ExercisesHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/routines_helper.rb
module RoutinesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def last_value_for_exercise(exercise, attribute)
    SessionExercise.joins(:routine_exercise)
                   .where(routine_exercises: { exercise_id: exercise.id })
                   .order(created_at: :desc)
                   .pick(attribute) || 0
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/exercises/index.html.erb
<div class="flex flex-col mb-8 md:mb-10 justify-between md:flex-row">
  <div>
    <h1 class="text-4xl mb-1">Add Exercise to Routine</h1>
  </div>
  <%= link_to 'Back to Routines', group_routine_path(@routine.group, @routine), class: "self-start md:self-center rounded-md bg-white px-3 py-2 mt-2 text-sm font-semibold text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 hover:bg-gray-50" %>
</div>

<%= link_to "Create a new Exercise", new_group_routine_exercise_path(@routine.group_id, @routine), class: "rounded-md bg-white px-3 py-2 text-sm font-semibold text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 hover:bg-gray-50"%>

<% @categories.each do |category| %>
  <% category_exercises = @category_exercises[category.id] %>
  <h3 class="text-lg font-semibold text-gray-900 mb-2 mt-6"><%= category.name %></h3>
  <ul role="list" class="divide-y divide-gray-100 overflow-hidden bg-white shadow-sm ring-1 ring-gray-900/5 sm:rounded-xl">
    <% category_exercises.each do |exercise| %>
      <%= link_to (group_routine_add_exercise_path(@routine.group_id, @routine, exercise_id: exercise.id)), data: { turbo_method: :post } do %>
        <li class="relative flex justify-between items-center gap-x-6 px-4 py-5 hover:bg-gray-50 sm:px-6 ">
          <div class="flex min-w-0 gap-x-4">
            <div class="min-w-0 flex-auto">
              <p class="text-sm text-gray-900">
                <%= exercise.name %> <br/>
              </p>
            </div>
          </div>
        </li>
      <% end %>
    <% end %>
  </ul>
<% end %>

app/views/exercises/new.html.erb
<div class="flex flex-col mb-8 md:mb-10 justify-between md:flex-row">
  <div>
    <h1 class="text-4xl mb-1">Create your own Exercise</h1>
  </div>
  <%= link_to 'Back to Exercises', group_routine_exercises_path(@routine.group, @routine), class: "self-start md:self-center rounded-md bg-white px-3 py-2 mt-2 text-sm font-semibold text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 hover:bg-gray-50" %>
</div>

<%= form_with model: @exercise, url: group_routine_exercises_path(@routine.group, @routine), data: { turbo_method: :post } do |form| %>
  <%= form.label :name, class: "block text-sm font-medium leading-6 text-gray-900" %>
  <%= form.text_field :name, required: true, class: "block rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6" %>

  <%= form.label :category_id, class: "block text-sm font-medium leading-6 text-gray-900" %>
  <%= form.collection_select :category_id, @categories, :id, :name, include_blank: true, required: true, class: "mt-2 block w-full rounded-md border-0 py-1.5 pl-3 pr-10 text-gray-900 ring-1 ring-inset ring-gray-300 focus:ring-2 focus:ring-indigo-600 sm:text-sm sm:leading-6" %>
  <%= link_to 'New Category', new_group_routine_category_path(@routine.group, @routine), class: "self-start md:self-center rounded-md bg-white px-3 py-2 mt-2 text-sm font-semibold text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 hover:bg-gray-50" %>

  <%= form.label :exercise_type_id, class: "block text-sm font-medium leading-6 text-gray-900" %>
  <%= form.collection_select :exercise_type_id, @exercise_types, :id, :name, include_blank: true, required: true, class: "mt-2 block w-full rounded-md border-0 py-1.5 pl-3 pr-10 text-gray-900 ring-1 ring-inset ring-gray-300 focus:ring-2 focus:ring-indigo-600 sm:text-sm sm:leading-6" %>

  <%= form.submit "Create Exercise", class: "block mt-3 rounded-md bg-white px-3 py-2 text-sm font-semibold text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 hover:bg-gray-50" %>
<% end %>